version: '3.8'

services:
  db:
    image: postgres:15
    container_name: axelor-db
    environment:
      POSTGRES_DB: axelor
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U axelor -d axelor"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  axelor:
    build: .
    container_name: axelor-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8084:8080"

volumes:
  db_data:

