version: '3.8'

services:
  db:
    image: postgres:15
    container_name: axelor-db
    environment:
      POSTGRES_DB: axelor
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  axelor:
    build: .
    container_name: axelor-app
    depends_on:
      - db
    ports:
      - "8084:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: axelor
      DB_USER: axelor
      DB_PASS: axelor

volumes:
  db_data:

