version: "3.9"

networks:
  axelor-net:

services:
  db:
    image: postgres:15
    container_name: axelor-db
    environment:
      POSTGRES_DB: axelor
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor
    ports:
      - "5432:5432"
    networks:
      - axelor-net

  axelor:
    build: .
    container_name: axelor-app
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "8084:8080"
    networks:
      - axelor-net




