version: '3.8'

services:
  db:
    image: postgres:13
    container_name: axelor-db
    environment:
      POSTGRES_DB: axelor
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  axelor:
    build: .
    container_name: axelor-app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: axelor
      DB_USER: axelor
      DB_PASS: axelor
    depends_on:
      - db
    ports:
      - "8084:8080"

volumes:
  db_data:

